elmish/Elmish.WPF

src/Elmish.WPF/Binding.fs

As mentioned in #17, this allows commands to to be requeried for their CanExecute when the CommandManager suggests requerying, such as when the UI changes.  This allows buttons to become enabled/disabled by the state of the UI, even for situations where the model is not updated, such as when the CommandSource is binding the CommandParameter to a UI property.

Allow commands to requery CanExecute from CommandManager

---

README.md

The sample in the README was a bit incomplete. I needed to fiddle around to get it running.
It was missing the needed references for the main project and also the resulting window looked quite ugly on first run, so I tweaked the XAML a bit.

Update README with more friendly sample steps

---

src/Elmish.WPF/Binding.fs

Some Documentation comments in Bindings.fs were off (i.e. `<paramref="get">` instead of `<paramref="map">` and some paramrefs were missing.

Fix Parameter documentation in Bindings.fs

---

README.md

I think I found some improvements to the documentation in README.md.  I made each type of change in a separate commit.  Feel free to squash to a single commit before merging.

Several copy edits in README.md

---

src/Samples/SubModelSeq.Views/MainWindow.xaml
src/Samples/SubModelSeq/Program.fs

Resolves issue #95.
I think this is one way to fix the bug.  I switched the model from representing the graph (abstractly) as a list vertices and a list of edges to representing it directly.  Specifically, I created
```
module Tree =
type Node<'a> =
{ Data: 'a
Children: Node<'a> list }
```
which seems to be what Haskell calls a [Rose Tree](https://en.wikipedia.org/wiki/Rose_tree).
I just got it working, so my code might be a bit messy.  I can clean it up still in this PR or in a future one.

Fix reordering bug in tree view sample

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/ViewModel.fs

Exposes optional dispatch wrapping for `TwoWay`, `TwoWayValidate`, `SubModelSelectedItem`, `Cmd` and `CmdParam`, which is enough to enable users to throttle, debounce, or rate limit each message source #114.  In a future PR, we can make it easy for users to do those three things.

#114 wrap dispatch in bindings

---

src/Elmish.WPF/Binding.fs

The DU `BindingData` has several cases, just three of which are recursive (by referencing `Binding` which references `BindingData`).  The non-recursive cases don't need to be defined using `and`.
Given these types, I removed all unnecessary uses of `and`.  All remaining uses of 'and' for these binding data types are necessary.

reduced circular references among BindingData

---

src/Elmish.WPF/Binding.fs
src/Samples/SubModelSeq/Program.fs

I made the following small improvements while reading the code today.
The code compiles, all tests pass, and I tried all the features in all the samples.
The most important change was adding additional type parameters to the binding data records, which is related to #116.  This is helpful for two specific reasons.
1. It is now possible to understand how the functions in each binding data record are related by looking at the definition of the record.  Without this change, I constantly had to go look at the arguments of the various overloaded methods (where the types were still as strong as possible) to see how the functions are related.  (Of course, that is also how I figured out what the type parameters should be in order to make this change.)
2. We are closer to my goal of separating (1) …

Code clean up 2019-09-20

---

src/Samples/EventBindingsAndBehaviors/Program.fs
src/Samples/NewWindow/Program.fs
src/Samples/OneWaySeq/Program.fs
src/Samples/SingleCounter/Program.fs
src/Samples/SubModel/Program.fs
src/Samples/SubModelOpt/Program.fs
src/Samples/SubModelSelectedItem/Program.fs
src/Samples/SubModelSeq/Program.fs
src/Samples/UiBoundCmdParam/Program.fs
src/Samples/Validation/Program.fs

In some issue (which I was unable to find last time I looked), we discussed simplifying `init` from a function to a value in the Counter samples.  I did this for the SimpleCounter and SubModel samples.
Then I tried to make a similar change to the SubModelSeq sample.  I tried to extract the Counter code so that it looks essentially identical to the other two samples.  That didn't work.  It seems difficult to have a `SubModel` binding within a `SubModelSeq` binding.  Included some code clean up for the SubModelSeq sample anyway.  There was an unused binding.
I noticed that the NewWindow sample used `mkProgramWpf` even though it always returned `Cmd.None` for the command, so I simplified that to `mkSimpleWpf`.
Lastly is minor code clean up in all other samples.
I didn't test anything yet.  I …

Improve samples

---

src/Elmish.WPF/Binding.fs
src/Elmish.WPF/ViewModel.fs

Closes #33
@bender2k14 does this PR look good to you from a boxing/unboxing/type perspective?
By the way, the diff "boundaries" are a bit weird around the new `Binding` overloads. I have simply changed the `getWindow` signature for each of the three `subModelWin` overloads (with slight edits to the docs), and made copies of each of them with the old signature, delegating to the new. The diff makes it seem like I have made extensive edits to the docs because it has identified the "wrong boundaries", so to speak.

Make model/dispatch available to getWindow in Binding.subModelWin

---

src/Elmish.WPF/Binding.fs

I made a small mistake in #123.  As clearly seen here...
https://github.com/elmish/Elmish.WPF/blob/10b4deb160cbe1808e4d2f68ebd9c772e48d0ecc/src/Elmish.WPF/Binding.fs#L396-L401
...the type of `getId` in `OneWaySeqLazyData` should be `'b -> 'id`, not `'a -> 'id`.

corrected type parameter of getId in OneWaySeqLazyData

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/ViewModel.fs

Second of two PRs to resolve #135.  It "moves" three failure points "ahead" in the computation.  Instead of _eventually_ throwing an exception in one of three methods, the exception is now thrown "much sooner" in `initializeBindings`.
I removed a test that ensured that an exception is thrown in those three methods.  I did _not_ add a "replacement" test that ensures `initializeBinding` throws an exception in a similar case.
I created an explicit comparison function for sorting binding data.  I considering deriving this ordering from the order in which the cases are defined in the DU.  For example, in Haskell, this would [look like](http://learnyouahaskell.com/making-our-own-types-and-typeclasses) `data Bool = False | True deriving (Ord)`.  However, I wasn't able to determine if such a …

SubModelSeq into SubModelSelectedItem

---

src/Elmish.WPF/ViewModel.fs

https://github.com/elmish/Elmish.WPF/blob/4c8d85c58a6adbd7db1158be4fb3e9525f7be45c/src/Elmish.WPF/ViewModel.fs#L580-L591
I think the reason that `propsToNotify` and `cmdsToNotify` are `list`s instead of `seq`s is so that they are eagerly computed before the mutation on line 589.  However, I don't see any reason why `bindings` needs to be converted to a `list` ASAP (via lines 582 and 587).  In particular, after all bindings are initialized (in the same scope where the dictionary was instantiated), the `bindings` dictionary is only ever read (i.e. it is never mutated).  I made this clear by exposing the `bindings` dictionary as read only.
Therefore, I think it is a behavior preserving transformation to delay the calls to `Seq.toList` until the end of those expressions.

List to seq in UpdateModel

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/Elmish.WPF.Tests.fsproj
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/Elmish.WPF.fsproj
src/Samples/SingleCounter/Program.fs
src/Samples/SubModel/Program.fs
src/Samples/Validation/Program.fs

First commit modifies `fsproj` files to turn unused values into build warnings.  The second commit deletes one unused line of test code.  The third commit renames all unused values to `_`.

Unused values as warnings

---

src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/ViewModel.fs

Fixes #134 and partially addresses #137 by implementing all of the "simple" optimizations.
I have not tested anything yet.  I will test later.
The two remaining more complicated optimizations are removing all elements that need to be removed in nearly linear time (as [discussed here](https://github.com/elmish/Elmish.WPF/issues/137#issue-500916222)) and ordering in nearly linear time (as [discussed here](https://github.com/elmish/Elmish.WPF/issues/137#issuecomment-537744117)).

Simple observable collection optimizations

---

src/Elmish.WPF.Tests/ViewModelTests.fs

This syntax is strictly better:
1. It is shorter.
2. It is idiomatic.
3. It doesn't have a warning.  The previous code had a warning because `x` was unused (and we are using `--warnon:1182`) and [`x` can't be replaced by `_`](https://github.com/dotnet/fsharp/issues/7740).

simplified type check syntax

---

src/Samples/EventBindingsAndBehaviors.Views/EventBindingsAndBehaviors.Views.csproj

Upgrades [Microsoft.Xaml.Behaviors.Wpf](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/) to its latest version.  Compared to the previous version that we were using that only targeted .NET Framework, this version also targets .NET Core.  This removes two build warnings for us since we target both of those now.
I tested the `EventBindingsAndBehaviors` sample, which is the only code that depends on this NuGet package.  Everything still works.

upgraded Microsoft.Xaml.Behaviors.Wpf to version 1.1.3

---

src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/ViewModel.fs

Fixes #150 
I am very open to suggestions for improvement on this code.  My primary goal was to quickly give us something concrete to discuss.
I didn't try to deduplicate anything, and I am not jazzed about how I used `if-then` to skip over the happy path in `updateValue`.  However, I think this behavior is ideal.  Otherwise, no other bindings are updated after encountering this issue.

improves the error handling when getId returns duplicates

---

src/Samples/EventBindingsAndBehaviors.Views/MainWindow.xaml
src/Samples/EventBindingsAndBehaviors/Program.fs

Partially addresses #33.
Only changes the `EventBindingsAndBehaviors` sample.  I tested it, and everything works.

Example usage of PassEventArgsToCommand

---

src/Elmish.WPF/Elmish.WPF.fsproj
src/Elmish.WPF/ViewModel.fs

Fixes #175.
Specifically, this PR
1. replaces the eager behavior with the intended lazy behavior (by only calling `getSelectedSubModel` if `!b.Selected` is in the `ValueSome` state and
2. returns `true` if and only if `!b.Selected` is mutated (either one of its `voption`s is in a different state or they are both in the `ValueSome` state and the new view-model is not reference equal to the old one).
I tested the `SubModelSelectedItem` sample, and everything still works.

Improve updateValue for SubModelSelectedItem

---

src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/ViewModel.fs

Fixes #181 
Creates a recursive binding type called `CachedBinding<'model, 'msg>`.  The caching in the `OneWayLazy` and `SubModelSelectedItem` cases are removed and now use this cached binding instead.
All the tests pass, and there is an existing test for `OneWayLazy` that ensures that caching is working.
I left one comment in the code to make sure we have a conversation about it.  I will create a comment in this PR on that line next.

Recursive cached binding

---

README.md

Binding.twoWay takes a tuple. This code example would not run as it was.

Update Readme to fix call to Binding.twoWay

---

README.md

Fixed an issue withe the code example that tripped me up when I was trying to get started and didn't want others to have the same initial experience. 
`Program.mkSimpleWpf` is not able to be found unless you've opened `Elmish.WPF` instead of `Elmish`.

Documentation: Fixed a typo in the Program.fs open statement

---

src/Elmish.WPF/Program.fs

Fixes #200
`Application.Current` in
https://github.com/elmish/Elmish.WPF/blob/3f0d3552203dcf3152f1088014ee608f2926f8a9/src/Elmish.WPF/ViewModel.fs#L199
was `null` when processing an initial state as described in #200.  After some clean up of the relevant code, this is a minimal change to fix that bug.
I didn't create an automated test for this bug.  As is, it needs to display one or two windows.  I have created a WPF test before (which needs to execute with a dedicated thread), but I have never tried to display a window in a test before, and I don't feel like trying to do that now.
There is another way to fix this bug that I will suggest in a new issue.

Bug fix 200 current application

---

src/Elmish.WPF/Program.fs
src/Elmish.WPF/ViewModel.fs

This is a better fix to issue #200, which has already been fixed by PR #201.  This change also allows additional windows to be created in different threads.
Some related discussion is also in issue #202 (but I will include here the parts that I think are most relevant).
In https://github.com/elmish/Elmish.WPF/issues/202#issuecomment-613543070, I said
> ...the thought about which `Dispatcher` instance to use crossed my mind, but I don't know the difference between using one vs another.
I read up on this, and I think I understand this now.  The short answer is that each WPF object instance can only be modified by the thread that created it.  Don't know what thread created a certain WPF object instance?  No worries; just mutate that instance using its `Dispatcher` instance.
This is what …

Use window dispatcher

---

src/Elmish.WPF/Program.fs

Fixes #206
As @cmeeren suggested in https://github.com/elmish/Elmish.WPF/issues/206#issuecomment-618504164, this PR initializes `Application` and shows the provided `Window` before starting the Elmish dispatch loop.
One additional change is also needed though, which is to set the provided window to `Applicaiton.Current.MainWindow`.  The [documentation](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/how-to-get-and-set-the-main-application-window) says that...
> The first Window that is instantiated within a Windows Presentation Foundation (WPF) application is automatically set by `Application` as the main application window.
...but this is only true if `Application` has been instantiated.  Therefore, this PR also assigns the provided `Window` to …

initialize main Window before starting Elmish dispatch loop #206

---

src/Elmish.WPF.Tests/ViewModelTests.fs

As I work on draft PR #214, I want to split off self-contained changes into separate PRs.  Here is one such change.
I think the use of the `list` type is simpler than using the `array` type in these tests.  Specifically, several definitions of `map` have changed from `Array.toList` to `id` and some type annotations are now gone.
I think `array` was originally chosen over `list` in some of these cases because there was some limitation with F#'s type inference with some of the code in quoted expressions.  That limitation was overcome by adding type annotations.
Instead, this PR
1. moves functions with types to be inferred out of quoted expressions,
2. removes the unneeded type annotations, and then
3. replaces uses of the `array` type with the `list` type.

Replace uses of array type in tests with list type

---

src/Elmish.WPF.Tests/ViewModelTests.fs

The tests for adding or removing an element only did so at the end of the list.
This PR utilizes `GenX.addElement` to test adding or removing an element from any position of the list.

test adding and removing from any index instead of just at the end

---

src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/ViewModel.fs

I think this code should only call `get` twice, once for the current model and once for the new model.
The previous code called `get` three times, once for the current model and _twice_ for the new model.
This PR saves the return value from the first time the new model is passed into `get` and uses that in place of another call to `get`.

Remove one call to `get`

---

src/Elmish.WPF.Tests/ViewModelTests.fs

This PR primarily improves test names.  It also splits one test in two (because after which, the name each name is easier to understand).  It also removes two more type annotations I missed before (after extracting the corresponding functions from within a quoted expression).

Improve test names

---

src/Elmish.WPF/ViewModel.fs

This PR extracts the aspects of `oneWaySeqMerge` and `SubModelSeqMerge` that differ.
The next PR in this sequence will rename identifiers in these methods to confirm they are really the same function by observing they have exactly the same source code.  Then the PR after that will delete one of these functions and keep the other.

Unify OneWaySeq and SubModel merges

---

src/Elmish.WPF.Tests/ViewModelTests.fs

Two existing tests tested update after reversing the order of the elements.  This PR increases the scope of that test using `GenX.shuffle` to consider any permutation of the elements instead of just the reversal (though the identity permutation is excluded).

Test any permutation of elements

---

src/Elmish.WPF/ViewModel.fs

This PR changes identifiers, comments, and formatting of `oneWaySeqMerge` and `subMdoelSeqMerge`.  Now when I copy-paste the source of one onto the other, there is no source code change (detected by git).
The diff of the first commit is complicated, but I essentially repeat the commit message here that the only changes were done via Refactor->Rename in Visual Studio (except for where I added a comment when I found unneeded code).
The next PR will delete one of these functions.

Unify merges source

---

src/Elmish.WPF.Tests/ViewModelTests.fs

This PR primarily removes unused ID values in `OneWaySeqBinding` and `SubModelSeqBinding` tests.  It also improves some other minor things that I found in the process.
I will merge once the automated build completes successfully.

Remove unused ID values in tests

---

src/Elmish.WPF.Tests/ViewModelTests.fs

Partially addresses #229.
This PR strengthens the assertions of many merge tests from just verifying that some `CollectionChanged` event was raised to verifying that the state of the `ObservableCollection<>` is correct.
I will merge it once the build completes successfully.

Stronger merge assertions

---

src/Elmish.WPF.Tests/Elmish.WPF.Tests.fsproj
src/Elmish.WPF.Tests/MergeTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs

Partially addresses #229.
This PR replaces some `OneWaySeqBinding` and `SubModelSeqBinding` tests that were really only testing merge behavior with simplified and unified merge-focused tests.
I will merge this when the build completes successfully.

Unify merge tests

---

src/Elmish.WPF.Tests/MergeTests.fs

This PR adds a merge test for when a single item is moved (and some other minor improvement I found in the process).
I will merge this after the build completes successfully.

Test merge with one item moved

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/Elmish.WPF.Tests.fsproj
src/Elmish.WPF.Tests/InternalUtils.fs
src/Elmish.WPF.Tests/MergeTests.fs
src/Elmish.WPF.Tests/UtilsTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs

I couldn't help myself.  This will be the last such split.  I will complete PR #214 after this one completes.
This PR mostly adds assertions to existing merge tests to ensure that `create` and `update` are called the correct number of times.  When we improved the optimization of `emlStyleMerge` from https://github.com/elmish/Elmish.WPF/pull/214#issuecomment-630435425 to https://github.com/elmish/Elmish.WPF/pull/214#issuecomment-631087578, it was by only calling `create` if necessary.  With the assertions added in this PR, the original (less optimized) version of `elmStyleMerge` would now cause some tests to fail.
This PR also adds a test for a swap of two elements that are not necessarily adjacent and improves the organization of the test utility …

Count calls to create and update

---

src/Elmish.WPF.Tests/MergeTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs

Replacing calls to `Range.exponential` with `Range.constant` seems like an easy way to avoid issue #237.  For this branch, all the tests pass on my machine, which is using MSBuild 16.6.0.  Since AppVeyor is still using version 16.5.0, I expect all tests to pass for both the current state of `master` as well as for this branch.
I am not confident in my understanding of the difference between `Range.exponential` and `Range.constant`.
Does `Range.constant x y` model the ([discrete](https://en.wikipedia.org/wiki/Discrete_uniform_distribution) or [continuous](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous))) uniform distribution  and `Range.exponential` model either the [(discrete) geometric distribution](https://en.wikipedia.org/wiki/Geometric_distribution) or the …

Replaced calls to Range.exponential with Range.constant to avoid issue #237

---

src/Elmish.WPF.Tests/Elmish.WPF.Tests.fsproj

Fixes #238 
Test project now also targets .NET Core 3.0.
I will complete this after I see the automated build succeed.

Also target .NET Core 3.0 in tests

---

src/Samples/SubModelSeq/Program.fs

This PR only changes code in the `SubModelSeq` sample.
At a high level, the changes are to use more higher-order functions in order to be both more succinct and have more reusable code.
My intention is for the behavior to be unchanged.  I also expect the performance to be the same.  These changes are _not_ trying to address #236.
I tested this, and I think everything still works the same.
@ScottHutchinson, I think you will be interested in these changes since [you are using a `SubModelSeq` binding](https://github.com/elmish/Elmish.WPF/issues/143#issuecomment-641532812).

SubModelSeq update logic now more functional

---

src/Samples/SubModelSeq/Program.fs

PR #241 recently improved the code of the `SubModelSeq` sample.  One of the more suspicious changes was the existence and use of `Func.Dedup`.  We discussed that in https://github.com/elmish/Elmish.WPF/pull/241#discussion_r459087478.
With help from Twitter, I now know that this function is `flatten` for the function moand.  Specifically, `'a -> 'b` is a monad in `'b`.
There was a concern with the call site of this `flatten`, which was
```F#
let swapCounters swap nId =
nId
|> hasId
|> List.tryFindIndex
>> Option.map swap
>> Option.defaultValue id
|> Func.flatten
|> RoseTree.mapChildren
```
Quoting https://github.com/elmish/Elmish.WPF/pull/241#discussion_r459484715.
> The call side mixes piping and composition, which I find confusing, so it may be better to rewrite it. We'll see.
I now …

simplify SubModelSeq sample by using bindFunc

---

src/Samples/SubModel.Views/CounterWithClock.xaml
src/Samples/SubModel.Views/MainWindow.xaml
src/Samples/SubModelOpt.Views/MainWindow.xaml

I got a reply on [the issue](https://developercommunity.visualstudio.com/content/problem/1133390/design-time-data-in-datacontext-binding-not-displa.html) I created in the Visual Studio Developer Community.  The same issue was reported three weeks ago, and a workaround was found.  This PR implements that workaround.
Quoting https://github.com/elmish/Elmish.WPF/pull/249#issuecomment-668010074
> I think of Visual Studio Developer Community as the place where issues go to die. I would much rather create an issue on GitHub. However, I think the instruction not to post an issue with the XAML designer is clear and doing so risks angering the people best able to fix the problem.
I need to eat my words.  They did a great job this time.
Quoting …

implemented workaround for .NET Core design-time data binding bug

---

src/Elmish.WPF.Tests/Elmish.WPF.Tests.fsproj

When I build Elmish.WPF with Visual Studio, the official list of errors and warnings is empty.  However, the build output includes
```
20>------ Build started: Project: Elmish.WPF.Tests, Configuration: Debug Any CPU ------
20>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "PresentationCore". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
20>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly …
```

switched to obtaining WPF dependencies via UseWpf=true in the test project

---

RELEASE_NOTES.md
TUTORIAL.md
src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/ViewModel.fs
src/Samples/SubModelSeq.Views/Counter.xaml
src/Samples/SubModelSeq/Program.fs

This PR is a merge into the new branch `v4`.  It replaces the draft PR #244.
@cmeeren, there are conflicts between this branch and your logging branch.  Do you mind if we review and complete this PR first and then you resolve the conflicts with your logging branch?

Remove wrapDispatch and add mapMsgWithModel

---

RELEASE_NOTES.md
src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/Elmish.WPF.fsproj

This PR implements the `oneWaySeq` binding method via the `oneWaySeqLazy` method with `equals` = `refEq` and `map` = `id`.
I described more about this branch in https://github.com/elmish/Elmish.WPF/issues/253#issuecomment-671707215.
The only documentation I changed was in the `///`-style documentation above the relevant binding method.

#157 one way seq via one way seq lazy

---

src/Elmish.WPF/Elmish.WPF.fsproj

This PR is similar to PR #254
This PR removes direct references to the WPF DLLs in the project file of the main project since these dependencies are also being picked up via `<UseWpf>true</UseWpf>`.
I will complete this PR after the automated build finishes successfully.

removed direct references to WPF DLLs

---

src/Samples/SubModelSeq/Program.fs

Fixes #236
This PR greatly improves the performance of the SubModelSeq sample.
The first improvement is to maintain the tree structure when providing the data to Elmish.WPF and WPF.  In particular, each child is now given in a pair with its parent.  This makes going from a child to a parent a constant-time operation.  Previously, the entire tree was traversed to find the parent.
The second improvement is to maintain as much of the immutable tree data structure when making a change to the tree.  The process to make a change in the tree now traverses the tree directly to the change point, makes the change, then rebuilds the traversed parts of the tree.  Previously, the entire tree was traversed to find the change point, so the whole tree had to be rebuilt.

Optimize SubModelSeq

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/ViewModel.fs
src/Samples/Validation.Views/MainWindow.xaml
src/Samples/Validation/Program.fs

Resolves #314
This PR adds support for multiple validation errors.
Here are some interesting points about this implementation.
- Other than adding to the API support for a list of errors, I left the existing API as is.  Internally, I converted each `Option` and `ValueOption` to a `list`.
- Equality of errors is done by the equality for `string list`.  This means that the order of errors matters.  I think that is reasonable.
- The sample still includes the previous code in which there is only one validation error.  I added another text box that includes multiple validation errors.
- To quickly get this PR working, the `Submit` message in the sample no longer takes in the parsed data.  However, doing so is preferred.  As Mark Seemann [recently …

Support for multiple validation errors #314

---

RELEASE_NOTES.md
src/Elmish.WPF/WpfProgram.fs
src/Samples/SubModelOpt/MainWindow.xaml

We are showing the window too early.  We should only show the window after we assign our view model to its `DataContext`.
Here is how this can go wrong.  Suppose the binding initialization code takes a long time.  In the following example, I added a two-second delay to the `SubModelOpt` sample.  I also removed the `Visibility` fallbacks to `Collapsed`.  I also changed to entry point to be an explicit `Main` method.  Then this is what happens: both forms are visible during that two-second loading time.
After making the change in this PR, which is to start the Elmish dispatch loop first and then show the window, the behavior is good.  Specifically, the window does not open during that two second delay.  When it does open, no forms are visible, which is the correct behavior.

Set DataContext before showing window

---

README.md
RELEASE_NOTES.md
src/Elmish.WPF/Elmish.WPF.fsproj
src/Samples/FileDialogs.Core/Program.fs
src/Samples/FileDialogsCmdMsg.Core/Program.fs

I don't think the `save` or `load` functions need to be executed on the main thread.  This can be tested by adding the line
```fsharp
do! Async.SwitchToThreadPool ()
```
to the beginning of these CEs on this branch.  Everything still works.

Simplify FileDialog save/load

---

src/Elmish.WPF/ViewModel.fs
src/Elmish.WPF/WpfProgram.fs

Fixes #330
Fixes #353
Closes #355
Closes #358
Calling `Window.Close` is not allowed when the `Window` in question is in the process of closing.  In case that is the situation, we can avoid this below slightly delaying our call to `Window.Close` by using `Dispatcher.BeginInvoke`.

Close window and dispatch messages via Dispatcher.InovkeAsync

---

src/Samples/EventBindingsAndBehaviors.Core/EventBindingsAndBehaviors.Core.fsproj
src/Samples/FileDialogs.Core/FileDialogs.Core.fsproj
src/Samples/FileDialogsCmdMsg.Core/FileDialogsCmdMsg.Core.fsproj
src/Samples/NewWindow.Core/NewWindow.Core.fsproj
src/Samples/OneWaySeq.Core/OneWaySeq.Core.fsproj
src/Samples/SingleCounter.Core/SingleCounter.Core.fsproj
src/Samples/Sticky.Core/Sticky.Core.fsproj
src/Samples/SubModel.Core/SubModel.Core.fsproj
src/Samples/SubModelOpt.Core/SubModelOpt.Core.fsproj
src/Samples/SubModelSelectedItem.Core/SubModelSelectedItem.Core.fsproj
src/Samples/SubModelSeq.Core/SubModelSeq.Core.fsproj
src/Samples/UiBoundCmdParam.Core/UiBoundCmdParam.Core.fsproj
src/Samples/Validation.Core/Validation.Core.fsproj

Replaces #282
This PR removes the line
```xml
<UseWpf>true</UseWpf>
```
from all of `Core` sample projects.
Removing this line from these projects was not possible when PR #282 was created because we were still targeting .NET Core 3 (`netcoreapp3.0` or `netcoreapp3.1`).  Now we are targeting .NET 5 (`net5.0-windows`).  When this change was made in 77635638db374328b1d091d75ea38ca2d39e5989, the SDK was simplified.  I have now realized that we could have also removed this line as well.
@cmeeren, since you previously said in https://github.com/elmish/Elmish.WPF/pull/282#issuecomment-705178872 that you were indifferent to this kind of change, I will merge when the build successfully completes.

removed UseWpf in samples

---

src/Elmish.WPF/ViewModel.fs

Partially addresses #363.
The indentation changed, so be sure to view the diff while ignoring whitespace changes.
This PR replaces the "outer" use of the `async` computational expression in the `showNewWindow` function.
Contrary to my initial guess in #363, I was wrong about this use of `Dispatcher` being unnecessary.  As I also documented in a comment, `Dispatcher` is required here because the `Window` might be owned by a different thread (which I verified programmatically).
By calling `Async.StartImmediate`, the current thread is used to execute the CE.  That same thread is captured in `guiCtx`, so switching to it does nothing.  Except it does to one thing, which is cause the runtime to stop synchronous execution of this `Async` instance.  Instead of capturing and switching to the …

Replace async CE with InvokeAsync in showNewWindow

---

src/Elmish.WPF/ViewModel.fs

This PR deletes three lines and changes the indentation of one line, so it helps to view the diff while ignoring whitespace changes.
I think the `async` computational expression is not needed in the callback given to the `Window.Closing` event.  It might have been needed before.  Now though, invoking `dispatch` eventually leads to this asynchronous `Dispatcher` execution.
https://github.com/elmish/Elmish.WPF/blob/cdf421f9ec7c3ec4d6d3e3923cd20786004ed098/src/Elmish.WPF/WpfProgram.fs#L70

removed async CE in window closing event

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF/Binding.fs
src/Samples/UiBoundCmdParam.Core/Program.fs

This restored function is marked as obsolete with a suggestion to use the newly added alternate overload without the parameter.
Fixes #413

Restore the wrapDispatch parameter

---

src/Elmish.WPF/WpfProgram.fs

Fixes #426
I also added `withMsgErrorHandler`, where you supply a handler that returns `'msg list` instead of `unit`, and the returned messages are then dispatched by Elmish.WPF. As I said in https://github.com/elmish/Elmish.WPF/issues/426#issuecomment-916045586, this functionality can be implemented in user code, but it requires more boilerplate impure code (events/subscriptions) and was so trivial to implement in Elmish.WPF that I see no compelling reason not to support it.

Add withErrorHandler and withMsgErrorHandler

---

src/Elmish.WPF/ViewModel.fs

This gives a list of member names in the debugger window along with the values. It makes debugging much easier.
I based this branch off of beta-41 because that's what our project uses, and beta-42 breaks a bunch of things in our project. It should work in both places though.

Add GetDynamicMemberNames override to make debugging easier

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/BindingInternal.fs
src/Elmish.WPF/ViewModel.fs

Allow Statically-typed View Models pt 1
It's not as big as it looks: a major change was to move most of the contents of Bindings.fs into a separate file without modification (first commit). Perhaps that could be a different Pull Request.
The big advantage to this refactor is that it fully decouples all of the binding logic from the actual type of the `ViewModel`, which is going to be important if we want those to be statically typed later on (See #447 for a very rough proof-of-concept).

Remove dependency on ViewModel Class type in Binding Data.

---

src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/MergeTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/BindingInternal.fs
src/Elmish.WPF/InternalUtils.fs
src/Elmish.WPF/Merge.fs
src/Elmish.WPF/ViewModel.fs

Add a `CollectionTarget<'a>` so that we can properly box and unbox the collections so that they have the strongest type under the hood.

Add CollectionTarget so that SubModelSeq's can be properly typed

---

src/Elmish.WPF.Tests/ViewModelTests.fs

The last PR had a bug where we missed one rename #460

Fix renaming issue with fake->none

---

src/Elmish.WPF/BindingInternal.fs
src/Elmish.WPF/ViewModel.fs

Strongly type get and set binding data. This doesn't actually affect much, but it allows for some very helpful things later. Also it matches consistency with the other parts of the code, which technically *could* use `obj` everywhere but don't.

Strongly type Get and Set Binding Data

---

RELEASE_NOTES.md
src/Elmish.WPF.Tests/BindingTests.fs
src/Elmish.WPF.Tests/ViewModelTests.fs
src/Elmish.WPF/BindingInternal.fs
src/Elmish.WPF/BindingVmHelpers.fs

Each recursive binding case should either do model/msg mapping on its own functions or its inner binding but not both.
Somewhat annoyingly, this increases duplicate code (which is why I didn't write it this way in the first place).  I wonder if there is a good way to dedup this.
This is also a good reminder that I should write more (view model) tests.

Optimize lazy effect by reducing calls to get

---

TUTORIAL.md

Thought it helpful to link the Tutorial sections directly to the referenced Samples source code.
NOTE: seems I may have deleted my previous pull request(?) by deleting my repo's source branch for the previous request.  I have made the requested changes: by marner2 to use relative links and by TysonMN that the supporting text for the relative links be "XAML views and F# core".

 Add links from Tutorial sections to relevant Samples code. #486 (second try)

---

src/Elmish.WPF.Tests/UtilsTests.fs
src/Elmish.WPF/InternalUtils.fs

Add some helpers that allow for converting between `ValueOption` and nullable values *without requiring* that `'a` be statically restrained as a nullable type. `toNull` will never generate `ValueNone` if the value is not nullable, and `ofNull` will throw an exception if you feed it a `ValueNone` when `'a` is a non-nullable value.
I'm doing it unchecked currently, but I don't know of any way to match/discriminate on a type between nullable and non-nullable. I'm pretty sure you *always* end up with the type parameter being constrained all the way up, or not able to call constrained functions (hence why the implementation has to use boxing).

Add ofNull and toNull to ValueOption

---

src/Elmish.WPF/Binding.fs
src/Elmish.WPF/BindingData.fs

First commit extracted out of #470, it seems to stand alone. Basically I extract boxing out of `BindingData.fs` and move it into `Binding.fs` for a more composable structure.

Move boxing out of BindingData

---

src/Elmish.WPF/BindingVmHelpers.fs

`TryGetMember` -> `TryGet`
`TrySetMember` -> `TrySet`
This is in response to confusion while debugging `DynamicViewModel.TryGetMember`.

Rename TryGetMember and TrySetMember to avoid confusion with system methods

---

src/Elmish.WPF/BindingData.fs
src/Elmish.WPF/BindingVmHelpers.fs
src/Elmish.WPF/DynamicViewModel.fs

This Pull Request adds another type parameter to `BindingData` which allows it to carry the actual view model property type statically through the builder.
From a conversation with @TysonMN:
> When used in the context of "dot" notation in the XAML project, you will be able to get compile-time help for things like ViewModelProp.SubModel.Prop. If those were constrained to obj, you wouldn't get compile-time checking of those types.
Also XAML will warn you about type issues (number vs string, etc)
Note that the current usage of `Binding<'model,'msg>` constrains the new type parameter to be `obj` for every construction of it (this is the entire public interface in `Binding.fs`). This is intentional, as all of those bindings are by necessity constrained to `obj` in order to work in the various …

Add output type information to `BindingData`

---

src/Elmish.WPF/BindingVmHelpers.fs

This PR is very similar to #459 in that we take a ref field and convert it to a getter and a setter that has a mutable backing value. This allows us to box/unbox it.
This will conflict with #511 because of it renaming `'value` to `'t`. It's an easy resolution.

Change typed refs in VmBindings to getset

---

src/Elmish.WPF.Tests/BindingVmHelpersTests.fs
src/Elmish.WPF/BindingVmHelpers.fs
src/Elmish.WPF/DynamicViewModel.fs

It was redundant to pass `dispatch` into the `Update` helper which was only used in cases of constructing new models for `SubModel...` cases. `dispatch` is passed down while constructing `VmBinding` records, which are in turn available in the `Update` call.
This reduces the api surface.
This will conflict with #475 where there are single line initializer lists where `GetVm` and `SetVm` gets added.

Remove dispatch from update

---

src/Elmish.WPF.Tests/UtilsTests.fs
src/Elmish.WPF/InternalUtils.fs

Make so that `ValueOption.ToNullError.ValueCannotBeNull` carries the name of the type that was attempted to be made null for error reporting purposes.

Make ToNullError carry the type information

---

TUTORIAL.md

The binding isn't called `subModelSeqSelectedItem` anymore. This PR updates the name in the tutorial.

Rename subModelSeqSelectedItem to subModelSelectedItem

---

src/Elmish.WPF.Tests/BindingVmHelpersTests.fs
src/Elmish.WPF/BindingVmHelpers.fs
src/Elmish.WPF/DynamicViewModel.fs

~~Waiting on #516~~ (merged)
Adds the output type parameter to the types contained in `BindingVmHelpers.fs` (`VmBinding` and the Get/Set/Update/etc)

Add output type parameter to BindingVmHelpers

---

REFERENCE.md

The headers underlined with hyphens are H2, I gather. I had been treating them as H1 and thus making their children H2. This changes their children to H2 and grandchildren H3.

Indent headers to distinguish H2 from H3 in REFERENCE

---

src/Elmish.WPF.Tests/BindingVmHelpersTests.fs
src/Elmish.WPF/BindingVmHelpers.fs

It always returns the same thing as `initialModel` at that point, and there are cases where this doesn't work (for example, if you are initializing all of the bindings and `getCurrentModel` uses a member access).

Don't call getCurrentModel on initialization

---

src/Elmish.WPF.Tests/BindingVmHelpersTests.fs
src/Elmish.WPF/BindingVmHelpers.fs
src/Elmish.WPF/DynamicViewModel.fs

Use getCurrentModel from Initialize instead of Update to create new view models
This removes need for `getCurrentModel` inside of `Update.Recursive`

Use getCurrentModel from Initialize instead of Update to create new view models

---

src/Elmish.WPF.Benchmarks/Program.fs
src/Elmish.WPF.Tests/DynamicViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/DynamicViewModel.fs
src/Elmish.WPF/WpfProgram.fs

Replace explicit instances of `DynamicViewModel` with an interface that will also apply to the future `ViewModelBase` and anything that implements it.
This is one commit out of #522 that I figured would be useful even separately. It will conflict with #523, but not too badly.

Use IViewModel instead of explicit types

---

src/Elmish.WPF/DynamicViewModel.fs

~~Should rebase easily after #535~~
This should be a behavior-preserving transform that extracts some behavior from `DynamicViewModel` into a `ViewModelHelper` which can then be shared with a future `ViewModelBase` implemented in #522

Extract a ViewModelHelper that will be useful with static view models

---

src/Elmish.WPF.Tests/DynamicViewModelTests.fs
src/Elmish.WPF/DynamicViewModel.fs

Found a bug in #523 that resulted in the events being fired too soon (before the view model's properties were updated). Also added a test that will verify this happening (tested that test fails before this PR).

Fix update timing issue

---

src/Elmish.WPF.Tests/UtilsTests.fs
src/Elmish.WPF/InternalUtils.fs

`unbox null` throws a `NullReferenceException`.
Thanks to @marner2 for figuring out the solution.

Do not throw NullReferenceException when ValueOption.toNull is called on ValueNone of reference type

---

src/Elmish.WPF.Tests/BindingVmHelpersTests.fs
src/Elmish.WPF.Tests/StaticViewModelTests.fs
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/BindingData.fs
src/Elmish.WPF/BindingVmHelpers.fs
src/Elmish.WPF/Elmish.WPF.fsproj
src/Elmish.WPF/Merge.fs
src/Elmish.WPF/ViewModels.fs
src/Samples/SubModelStatic.Core/Program.fs

Need this in Getter and Setter helpers where you need to keep the type around longer, but box/unbox it before storing/retrieving it from the static type's storage.
Implements full feature that allows for static type of binding specifiers to bubble all the way up to the property.
~~Merge after #511 and #475~~(Merged)
~~Should wait until after #522 so that it can include the actual usages (as explained below).~~
~~EDIT: this *may* not be necessary, as we may always be able to just unbox things on their way out once #512 is merged in in those getters.~~ Combined with #512

Make type of get/set propagate to static view model property

---

src/Elmish.WPF/WpfProgram.fs
src/Samples/SubModelStatic.Core/Program.fs
src/Samples/SubModelStatic/MainWindow.xaml

Should wait until after #522 so that it can include the extra helpers for having a static view model at the very top level.
Makes WpfProgram more flexible from the top level (very similar to `SubModel`)

Make WpfProgram more flexible

---

src/Elmish.WPF.sln
src/Elmish.WPF/WpfProgram.fs
src/Samples/Threading.Core/Program.fs
src/Samples/Threading.Core/Threading.Core.fsproj
src/Samples/Threading/App.xaml
src/Samples/Threading/App.xaml.cs
src/Samples/Threading/MainWindow.xaml
src/Samples/Threading/MainWindow.xaml.cs
src/Samples/Threading/Threading.csproj

The basic implementation of this PR would be to invoke all calls to the underlying dispatch on one thread, then invoke all calls to `UpdateViewModel` on the UI thread associated with the window.
However, WPF expects events to raise `NotifyPropertyChanged` events before they exit, otherwise things like textboxes will "reset" following the disconnected update coming from the elmish update thread. This causes, for instance, the cursor to jump to a different location as you are typing. This means that we cannot simply invoke the dispatch calls coming from WPF in an async manner - we must block that call until the elmish update thread has processed that update and generated `NotifyPropertyChanged` events. This block is ok, because any dispatch calls from the non-ui thread will dispatch the UI …

Make so elmish update and cmd loop can run on non-ui thread

---

RELEASE_NOTES.md
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/Elmish.WPF.fsproj

This is useful if you want to have a list of view models that all share the same model and msg. This list is maintained outside of the elmish loop, and is usually static.

Add SubModelT.seq

---

src/Samples/FileDialogsCmdMsg.Core/Program.fs
src/Samples/NewWindow.Core/App.fs
src/Samples/NewWindow.Core/AutoOpen.fs
src/Samples/NewWindow.Core/Program.fs
src/Samples/NewWindow.Core/Window1.fs
src/Samples/NewWindow.Core/Window2.fs

I found Sample/NewWindow.Core/App.fs hard to read. I have a version in [my fork](https://github.com/rfreytag/Elmish.WPF/tree/Adding_fully-specified_parameter_lists), branch: Adding_fully-specified_parameter_lists that I find more readable with the following changes:
Every function has fully-specified parameter lists and return values. Readability is improved by not having to hover over function names to see what the function manipulates.
module App, module Window1 and module Window2 have been renamed module App_Window1 and module App_Window2 so their usage in App.bindings is not confused with the actual references to Window2 in App.bindings.
Clarified module App, module Window1 and module Window2: get, set, and map so they specify the type on which they operate for readability. They are …

Adding fully specified parameter lists to NewWindow.Core and FileDialogsCmdMsg.Core

---

RELEASE_NOTES.md
src/Elmish.WPF/BindingVmHelpers.fs
src/Elmish.WPF/Elmish.WPF.fsproj
src/Elmish.WPF/ViewModels.fs
src/Elmish.WPF/WpfProgram.fs

Adds a caching feature for setters which allows us to notify property changed within the setter rather than waiting for UpdateModel to be called (which is more idiomatic within MVVM).
With this in play, the threaded behavior no longer has to block on potentially expensive ViewModel Updates in order to guarantee well-behaved TwoWay bindings on TextBoxes. Instead, we can schedule ViewModel Updates so that they "drop" intermediate Updates when they start piling up. This is possible because ViewModel Updates are fundamentally transitive with MVU. So for example, `vm.Update(model1); vm.Update(model2); vm.Update(model3);` always results in the same final view state as `vm.Update(model1); vm.Update(model3);`
This latter behavior only applies to Elmish in multithreaded mode. It does not change …

Improve threading behavior

---

RELEASE_NOTES.md
src/Elmish.WPF/Elmish.WPF.fsproj
src/Elmish.WPF/WpfProgram.fs

Improved implementation of #575 that doesn't result in inconsistent view model states on the UI thread.

Ensure that latest model is always applied in threaded case

---

RELEASE_NOTES.md
src/Elmish.WPF/Elmish.WPF.fsproj
src/Elmish.WPF/WpfProgram.fs

Ensures that `program.UpdateViewModel(vm, m)` is always run in the correct order, even when an immediate UI update is requested. This is done by scheduling a job cleanup in order with the other scheduled job adds, which will always execute before any jobs are executed (because of dispatcher priority)

Fix threading issue

---

src/Elmish.WPF/Binding.fs
src/Samples/SubModelStatic.Core/Program.fs
src/Samples/SubModelStatic/Counter.xaml
src/Samples/SubModelStatic/MainWindow.xaml

Add OneWaySeqT and an example demonstrating it.

Add OneWaySeqT

---

RELEASE_NOTES.md
src/Elmish.WPF/Binding.fs
src/Elmish.WPF/Elmish.WPF.fsproj

Needed a separate version for structs. Maybe there is a better way to do this.

Add opt and vopt helper functions
