elmish/Elmish.WPF

.gitmodules
=> Done via github deps in paket

.gitignore, src/Elmish.WPF/Program.fs
So you can start the program with an initial value other than unit.
=> Added support for run with

src/Elmish.WPF/Elmish.WPF.fsproj, src/Elmish.WPF/Program.fs, src/Elmish.WPF/ViewModel.fs, src/Elmish.WPF/ViewModelUtilities.fs
new ViewModelUtilities module
Program module refactored for using new module
threadDispatcher added to ViewModel constructor
=> Refactoring of Progam.fs

.paket/Paket.Restore.targets, RELEASE_NOTES.md, appveyor.yml, build.fsx, src/Elmish.WPF/ViewModelUtilities.fs, src/Samples/Validation/Program.fs
* Add function to easily create design-time view models
* Refactoring
=> Release 2.0.0-beta-3

src/Elmish.WPF/ViewModel.fs
This resolves #78
(Edit by @cmeeren for GH hook: resolves #74, resolves #10)
=> Make TrySetMember return true for known bindings

src/Elmish.WPF/ViewModel.fs
=> Bug fix 102 start using elm config.measure limit ms

src/Elmish.WPF/ViewModel.fs
While working on #114, I made many small code improvements.  All changes are meant to be behavior preserving.  I find it helpful to not keep changes to myself for too long, so I thought I would contribute this PR now.
=> Code clean up while working on #114

src/Elmish.WPF/paket.template
Added my name to NuGet author list as offered and suggested by @cmeeren in https://github.com/elmish/Elmish.WPF/pull/118#issuecomment-531777543
=> added my name to NuGet author list

src/Elmish.WPF/Binding.fs
Fixes unexpected code discussed in #116
=> Replaced three calls with unbox with calls to box

src/Elmish.WPF/ViewModel.fs
I improved the names in the `OneWaySeq` case of the function `updateValue` that is the focus of #131.  All names were changed using `Ctrl+R, R` in Visual Studio.  No names were shadowing before, and no names are shadowing now.  This is a behavior preserving transformation.
=> improved identifier names in the OneWaySeq case of updateValue

src/Elmish.WPF/ViewModel.fs
First of two PRs for #135.  This PR is intended to be a behavior preserving transformation, and I think it is.  The code compiles, and all the tests pass for me.  I tried all the samples, and everything worked.
I can squash the commits into one if you would prefer.  I am indifferent this time.
=> Records for vm binding cases

README.md, appveyor.yml, src/Elmish.WPF/Elmish.WPF.fsproj, src/Samples/EventBindingsAndBehaviors.Views/EventBindingsAndBehaviors.Views.csproj, src/Samples/EventBindingsAndBehaviors/EventBindingsAndBehaviors.fsproj, src/Samples/NewWindow.Views/NewWindow.Views.csproj, src/Samples/NewWindow/NewWindow.fsproj, src/Samples/OneWaySeq.Views/OneWaySeq.Views.csproj, src/Samples/OneWaySeq/OneWaySeq.fsproj, src/Samples/SingleCounter.Views/SingleCounter.Views.csproj, src/Samples/SingleCounter/SingleCounter.fsproj, src/Samples/SubModel.Views/SubModel.Views.csproj, src/Samples/SubModel/SubModel.fsproj, src/Samples/SubModelOpt.Views/SubModelOpt.Views.csproj, src/Samples/SubModelOpt/SubModelOpt.fsproj, src/Samples/SubModelSelectedItem.Views/SubModelSelectedItem.Views.csproj, src/Samples/SubModelSelectedItem/SubModelSelectedItem.fsproj, src/Samples/SubModelSeq.Views/SubModelSeq.Views.csproj, src/Samples/SubModelSeq/SubModelSeq.fsproj, src/Samples/UiBoundCmdParam.Views/UiBoundCmdParam.Views.csproj, src/Samples/UiBoundCmdParam/UiBoundCmdParam.fsproj, src/Samples/Validation.Views/Validation.Views.csproj, src/Samples/Validation/Program.fs, src/Samples/Validation/Validation.fsproj
=> Target netcoreapp3.0

src/Elmish.WPF.Tests/BindingTests.fs, src/Elmish.WPF/Binding.fs, src/Elmish.WPF/Elmish.WPF.fsproj
Replaces PR #158.  Will merge many similar changes into this internal branch as describe in https://github.com/elmish/Elmish.WPF/issues/143#issuecomment-543904477.
=> [Internal] optimize default OneWaySeq using refEq

src/Elmish.WPF/ViewModel.fs
I found these two pattern matches on `VmBinding<'model, 'msg>` that were almost identical.  This PR extracts the common code.
The main difference was the model (`initialModel` vs `currentModel`), which is now passed in to the new function.
The other difference was what to do when `ValueNone` is matched.  The update case called `removeError name` while the initial case did nothing.  I unified this by having the initial case now also call `removeError name` since `removeError` will also do nothing after not finding `name` in the `errors` dictionary.
In addition to the extracted function being called, this adds one call to `Dictionary.Remove` and one `if` check per `twoWayValidate` initialization.  Probably fine.
I am looking ahead to #151.  I expect this change to help a bit since this …
=> combined validation error set and update logic

src/Elmish.WPF/ViewModel.fs
Three records for three cases of `VmBinding<'model, 'msg>` both had `set` and `dispatch`.  When used, the output of `set` is always passed to `dispatch`, so this PR composes those two functions ASAP.
This is progress toward #151.  Now `TrySetMember` can be uniformly implemented by a single function `set: obj -> 'model -> bool`, which does what the new `set: obj -> 'model -> unit` does and then returns the appropriate `bool` that is first used to conditionally log and then returned to WPF.
=> Combined set and dispatch fields in VM Bindings

src/Elmish.WPF/ViewModel.fs
Preparing for #143.
After adding a recursive lazy binding case in `VmBinding<'model, 'msg>`, the logic that handles the different cases will also change to be recursive.  This PR extracts all of those pattern matches into their own functions.  I also removed the default case on one pattern match to make sure that I don't forget to add the new lazy case when the time comes.
The functions that will so be recursive are
1. `updateValidationError`
2. `updateValue`
3. `getCmdIfCanExecChanged`
4. `tryGetMember`
5. `trySetMember`
=> Extracts all pattern matches on VmBindings

src/Elmish.WPF/Binding.fs
Strengthens the types in `boxBindingData` from `obj` to either `'bModel` or `'bMsg`, which are short for "boxed model" and "boxed message" respectively.  This alone is a nice improvement.
Furthermore, this seems necessary for how I have started to implement lazy bindings (c.f. #143).  My current plan is to have the lazy binding data look like
```
type internal LazyData<'model, 'msg, 'bindingModel> = {
Get: 'model -> 'bindingModel
Equals: 'bindingModel -> 'bindingModel -> bool
Binding: Binding<'bindingModel, 'msg>
}
```
When creating the lazy binding, `bindingModel` needs to be boxed but `'msg` should not be boxed.  Thus, that sub binding needs to be boxed by passing in `unbox` for `unboxModel` but `id` for `unboxMsg` and `boxMsg`.
=> Strengthen types in boxBindingData

src/Elmish.WPF/ViewModel.fs
Related to #178 (c.f. https://github.com/elmish/Elmish.WPF/issues/178#issuecomment-549569400).
The outer `voption` was being used to achieve some semblance of lazy behavior, but barely any.
This PR replaces it with `Lazy<>` and uses it the same way that the `OneWayLazy` binding does.  This PR also optimizes `updateValue` by first comparing the IDs of `newModel` and `currentModel` and continuing if and only if this expression is `false`, which is also something that the `OneWayLazy` binding does.
I tested the `SubModelSelectedItem` sample, and everything still works.
Side note:
I pushed three minor commits to `master` before making this PR to help keep this PR clean.
=> In SubModelSelectedItem, replaced the outer voption with Lazy<>

src/Elmish.WPF/Binding.fs
I recently realized that `Binding<'model, 'msg>` is a ~co~ _contravariant_ functor in `'model`.  As such, there exists a function `map` with signature
```F#
('a -> 'b) -> Binding<'b, 'c> -> Binding<'a, 'c>
```
satisfying the ~co~ _contravariant_ functor laws.
This PR adds that function under the name `Binding.mapModel` (and the `list` variant as `Bindings.mapModel`) and then simplifies the boxing of a binding by making use of this new function.
The scope of both of those functions is public since I expect these could be useful to users.  (I am trying to make use of it as I clean up my Undo/Redo example https://github.com/elmish/Elmish.WPF/issues/195#issuecomment-621443558).
I tested the `SubModelSeq` sample and it still works.
(Side note: I want to define a similar function `mapMsg` under …
=> Add Bindings.mapModel

README.md
=> Adding a link to the Contributor guidelines

src/Elmish.WPF/ViewModel.fs
This PR only extracts the merge logic for `OneWaySeq` and `SubModelSeq` into their own functions.
In a future PR, I will unify these two functions.
=> Extract merges

src/Elmish.WPF.Tests/ViewModelTests.fs
This PR adds two tests (one for `OneWaySeqBinding` and one for `SubModelSeqBinding`) that replaces an element and then calls `update`.
=> adds tests that replace an element

src/Elmish.WPF/ViewModel.fs
This PR removes one of the duplicate merge functions and renames the remaining one to `historicalMerge`.  This performance of this function will soon be compared with `elmStyleMerge`.
=> removed duplicate merge function

src/Elmish.WPF/ViewModel.fs
This PR moves `historicalMerge` out of ViewModel into its own _`internal`_ module in the same file.  This makes it easier to test since now an instance of `ViewModel<,>` is not required.
=> move historicalMerge out of ViewModel

src/Elmish.WPF.Tests/ViewModelTests.fs
This PR adds two tests (one for `OneWaySeqBinding` and one for `SubModelSeqBinding`) that swaps adjacent elements.  In theory, this case is covered by the tests that randomly permutes all elements in the list.  However, the swapping of adjacent elements is a special case in Elm's merge, so I want a more explicit test of this case.
=> added tests for swap of adjacent elements

src/Elmish.WPF.Tests/MergeTests.fs, src/Elmish.WPF/ViewModel.fs
Fixes #137 
This branch implements [merge like Elm does](https://github.com/elm/virtual-dom/blob/master/src/Elm/Kernel/VirtualDom.js#L980-L1226).  I have tested it in my application at work, and the performance is clearly better.
However, I don't want to merge this PR yet.  I want to write more tests to cover all the branches.  Then I will write performance tests with BenchmarkDotNet and share those results here.
I am creating this PR before I am ready to merge as an invitation for feedback.
=> Use Elm-style merge

.gitignore, TUTORIAL.md, appveyor.yml, src/Elmish.WPF/Elmish.WPF.fsproj, src/Samples/SubModelSeq.Views/MainWindow.xaml, src/Samples/SubModelSeq/Program.fs
I wanted to bring `v4` back into sync with `master`.  The main issue was minor conflicts in the `SubModelSeq` sample after PR #266 was completed.  I also updated the tutorial to match the new `SubModelSeq` code.
I tested the `SubModelSeq` sample, and everything still works.
=> Merge master into v4

src/Samples/SubModel.Core/Program.fs, src/Samples/SubModel/Clock.xaml
Resolves #283
I tested the sample.  It works great.
=> changed SubModel sample to use radio buttons in recommended way #283

src/Samples/EventBindingsAndBehaviors/MainWindow.xaml
=> Enrich event bindings example with KeyBinding

src/Elmish.WPF/WpfProgram.fs
Fixes #373 
Fixes #371 (though I increasingly believe that the true cause is a bug in WPF)
#353 remains fixed
This PR adjusts the recent change made in PR #359.  One change in that PR was to asynchronously dispatch all messages to avoid a race condition when the `Dispatcher` is shutting down (c.f. #353).  However, this made the UI worse (c.f. #73 and #731).
So the obvious fix is to synchronously dispatch messages from the UI and asynchronously dispatch messages from commands.  The only difficulty is that Elmish doesn't support this.  Instead, I achieved that behavior via a hack.
@et1975, any thoughts about this hacky solution related to Elmish?
It is also worth pointing out that this PR removes one of the assumptions that I used to argue that PR #368 was a behavior preserving …
=> synchronously dispatch msgs from the UI and asynchronously from commands

src/Elmish.WPF/Binding.fs, src/Elmish.WPF/ViewModel.fs, src/Elmish.WPF/WpfProgram.fs
Fix a few typos in the code comments.
=> Fix a few typos in the comments

src/Elmish.WPF/ViewModel.fs
=> Replace uses of ! and := with .Value

src/Elmish.WPF/Binding.fs, src/Samples/Multiselect/App.xaml.cs, src/Samples/Multiselect/MainWindow.xaml.cs
=> Omit <summary> if no other XML tags

src/Elmish.WPF.Tests/ViewModelTests.fs, src/Elmish.WPF/ViewModel.fs, src/Elmish.WPF/ViewModelModule.fs, src/Elmish.WPF/WpfProgram.fs
Add `ViewModelArgs` and `LoggingViewModelArgs` records and pass them into `Initialize` and `Update` class helpers.
=> Add view model args and send them through Initialize and Update

src/Elmish.WPF/Elmish.WPF.fsproj, src/Elmish.WPF/ViewModel.fs, src/Elmish.WPF/ViewModelArgs.fs
Move ViewModelArgs into their own file and make them `internal`
=> Move ViewModelArgs into their own file

src/Elmish.WPF/ViewModel.fs
This was in response to [this discussion](https://github.com/elmish/Elmish.WPF/pull/449#discussion_r838047693) in #449
=> Add SelectedItemBinding type instead of tuples

src/Elmish.WPF.Tests/ViewModelTests.fs
This reverts commit dff0e25ecb81b434da5c8d630de2a0a2326c9fde.
=> Testing if PR can be merged when build fails

src/Elmish.WPF.Tests/ViewModelTests.fs, src/Elmish.WPF/Binding.fs, src/Elmish.WPF/DynamicViewModel.fs, src/Elmish.WPF/ViewModelModule.fs, src/Elmish.WPF/WpfProgram.fs
=> Rename `ViewModel<'model,'msg>` to `DynamicViewModel<'model,'msg>`

src/Elmish.WPF/BindingVmHelpers.fs
=> Minimize `and` types in binding vm helpers

RELEASE_NOTES.md, src/Elmish.WPF.Tests/DynamicViewModelTests.fs, src/Elmish.WPF/BindingVmHelpers.fs
=> Add cache tests

src/Elmish.WPF.Tests/BindingTests.fs, src/Elmish.WPF.Tests/DynamicViewModelTests.fs, src/Elmish.WPF/Binding.fs, src/Elmish.WPF/BindingInternal.fs
Move all internal create functions into `Binding.fs` and minor type mapping to `BindingInternal.fs`
=> Move create and mapMinorType functions to Binding and Internal consistently

src/Elmish.WPF/Binding.fs, src/Elmish.WPF/BindingData.fs
Ready when #472 is merged and branch is updated
=> Split out bindingdata create functions

src/Elmish.WPF/BindingVmHelpers.fs
https://github.com/elmish/Elmish.WPF/pull/470#discussion_r920187252
=> Refactor long line bindingvmhelpers

RELEASE_NOTES.md, src/Elmish.WPF.Tests/DynamicViewModelTests.fs, src/Elmish.WPF/DynamicViewModel.fs
Also added a test to make sure it won't happen again. This can cause some quite mysterious exceptions.
=> Repaired missing log argument

RELEASE_NOTES.md, src/Elmish.WPF/Elmish.WPF.fsproj
Had to bump up a bunch of stuff that had been mistakenly put under beta-44 in the release notes.
=> Release beta 45

src/Elmish.WPF.Tests/BindingVmHelpersTests.fs, src/Elmish.WPF.Tests/Elmish.WPF.Tests.fsproj
I separated out the test addition from PR #470. This can be merged separately.
=> Add test for binding vm helpers

src/Elmish.WPF/BindingData.fs, src/Elmish.WPF/BindingVmHelpers.fs, src/Elmish.WPF/Merge.fs
Separated this out from #470 to simplify that out.
=> Add collection type bindings

src/Elmish.WPF/Binding.fs, src/Elmish.WPF/BindingData.fs, src/Elmish.WPF/BindingVmHelpers.fs
@TysonMN Here are your requested changes to be made in a previous PR to !470.
=> Perform requested cleanup before 470

src/Samples/NewWindow.Core/AutoOpen.fs
Deleted unused code as discussed in a prior pull request (now closed by me).
=> Removed unused code.

TUTORIAL.md
Split off from #518 for easier review.
=> Remove effectless whitespace from tutorial

REFERENCE.md
This splits documentation of lazy bindings and the documentation of adding laziness and caching.
=> Update lazy binding documentation

src/Elmish.WPF/DynamicViewModel.fs
Split off from #523 per @TysonMN 's request
=> Move initializeBindingWithValidation out of the binding initializer

.gitignore, src/Elmish.WPF.Benchmarks/Elmish.WPF.Benchmarks.fsproj, src/Elmish.WPF.Benchmarks/Program.fs, src/Elmish.WPF.sln, src/Elmish.WPF/Elmish.WPF.fsproj
Add a project for running benchmarks with BenchmarkDotNet
=> Add a benchmark project

src/Samples/SubModelOpt.Core/Program.fs, src/Samples/SubModelOpt/Form2.xaml
=> Name elements of the SubModelOpt sample Form2 consistently

src/Elmish.WPF/DynamicViewModel.fs
Refactor the `ViewModelHelper` to use more F#-friendly `Map`s instead of `IReadOnlyDictionary`
=> Use maps instead of ireadonlydictionary

src/Elmish.WPF/DynamicViewModel.fs
Waiting on #547 
This makes a different usage of `getFunctionsForSubModelSelectedItem` less redundant.
=> Extract function into helper

src/Elmish.WPF/Binding.fs
=> Combine Seq.map and Seq.iter

src/Elmish.WPF/Binding.fs
Some content was copied from elsewhere with slight corrections.
=> Add XML comments for strongly-typed bindings

README.md, RELEASE_NOTES.md, src/Elmish.WPF/Elmish.WPF.fsproj
This version upgrades dependency to Elmish v4.0.1. The most significant change is with subscriptions.
=> Bump version beta 50

src/Samples/FileDialogsCmdMsg.Core/Program.fs, src/Samples/NewWindow.Core/App.fs, src/Samples/NewWindow.Core/AutoOpen.fs, src/Samples/NewWindow.Core/Program.fs, src/Samples/NewWindow.Core/Window1.fs, src/Samples/NewWindow.Core/Window2.fs
This reverts commit 35a4e47ebaa2db20bfcd3db81478942004e1e5ac.
=> Revert "Merge pull request #567 from rfreytag/Adding_fully-specified_parameter_lists"

RELEASE_NOTES.md, src/Elmish.WPF/BindingVmHelpers.fs, src/Elmish.WPF/Elmish.WPF.fsproj, src/Elmish.WPF/ViewModels.fs, src/Elmish.WPF/WpfProgram.fs
Reverts elmish/Elmish.WPF#575
Reverting this because it results in the view model being in an inconsistent state on the main thread.
=> Revert "Improve threading behavior"

RELEASE_NOTES.md
Added release note updates so that reverted beta-51 still lives on.
=> Add back beta-51 release notes

README.md, src/Elmish.WPF/Elmish.WPF.fsproj
Improve some documentation and add the README directly to the nuget package to improve the experience there.
=> Improve documentation readme

src/Elmish.WPF/BindingData.fs, src/Elmish.WPF/BindingVmHelpers.fs, src/Elmish.WPF/WpfProgram.fs
Adds measure to the new functions that were added recently.
Also adds debug level measure to top-level functions (shouldn't affect performance nearly as much, so one level higher than the other trace ones)
=> Add measure to new functions

RELEASE_NOTES.md, src/Elmish.WPF/Elmish.WPF.fsproj
Update version to beta-54
Should have the new readme file now.
=> Update version beta 54

src/Elmish.WPF/Binding.fs, src/Samples/SubModelStatic.Core/Program.fs
Add TwoWayT and an example demonstrating it.
=> Add TwoWayT
